language: node_js
cache:
  directories:
    - node_modules
notifications:
  slack: dadi:pnhiL60xOrm7GOglHUmb7xHK
  email: false
node_js:
  - '7'
  - '6'
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
services:
  - redis-server
